app/models/users.py
from datetime import datetime
from werkzeug.security import generate_password_hash, check_password_hash
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from flask import current_app
from flask_login import UserMixin
from app.extensions import db, login_manager


class Role(db.Model):

    __tablename__ = 'roles'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), unique=True)
    users = db.relationship('User', backref='role', lazy='dynamic')

    def __repr__(self):
        return '<Role %r>' % self.name


class User(UserMixin, db.Model):

    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(64), unique=True, index=True)
    username = db.Column(db.String(64), unique=True, index=True)
    role_id = db.Column(db.Integer, db.ForeignKey('roles.id'))
    date_joined = db.Column(db.DateTime, default=datetime.utcnow)
    password_hash = db.Column(db.String(128))
    confirmed = db.Column(db.Boolean, default=False)
    name = db.Column(db.String(64))
    location = db.Column(db.String(64))
    about_me = db.Column(db.Text())
    last_seen = db.Column(db.DateTime, default=datetime.utcnow)

    @property
    def password(self):
        raise AttributeError('password is not a readable attribute')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)

    def generate_confirmation_token(self, expiration=3600):
        s = Serializer(current_app.config['SECRET_KEY'], expiration)
        return s.dumps({'confirm': self.id})

    def confirm(self, token):
        s = Serializer(current_app.config['SECRET_KEY'])
        try:
            data = s.loads(token)
        except:
            return False
        if data.get('confirm') != self.id:
            return False
        self.confirmed = True
        db.session.add(self)
        db.session.commit()
        return True

    def ping(self):
        self.last_seen = datetime.utcnow()
        db.session.add(self)

    def __repr__(self):
        return '<User %r>' % self.username


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

app/views/users.py
from flask import Blueprint, abort, render_template, flash, redirect, url_for, request, current_app
from flask_login import login_required, current_user

from app.forms import EditProfileForm
from app.models import User
from app.extensions import db, photos
from PIL import Image


users = Blueprint('users', __name__, url_prefix='user')


@users.route('/<username>')
def user_profile(username):
    user = User.query.filter_by(username=username).first()
    if user is None:
        abort(404)
    return render_template('users/user.html', user=user)


@users.route('/edit-profile', methods=['GET', 'POST'])
@login_required
def edit_profile():
    form = EditProfileForm()
    if form.validate_on_submit():
        current_user.name = form.name.data
        current_user.location = form.location.data
        current_user.about_me = form.about_me.data
        db.session.add(current_user)
        flash('Your profile has been updated.')
        return redirect(url_for('users.user_profile', username=current_user.username))
    form.name.data = current_user.name
    form.location.data = current_user.location
    form.about_me.data = current_user.about_me
    return render_template('users/edit_profile.html', form=form)


@users.route('/<username>/upload-image',  methods=['POST'])
def upload_image(username):
    user = User.query.filter_by(username=username).first()
    if user is None:
        abort(404)
    if request.method == 'POST' and 'photo' in request.files:
        crop_x = request.form.get('cropx')
        crop_y = request.form.get('cropy')
        crop_w = request.form.get('cropw')
        crop_h = request.form.get('croph')
        photos.save(request.files['photo'])
        flash("Photo saved.")
    return render_template('users/user.html', user=user)

app/templates/users/edit_profile.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Flasky - Edit Profile{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>Edit Your Profile</h1>
</div>
<div class="col-md-4">
    {{ wtf.quick_form(form) }}
</div>
{% endblock %}

app/templates/users/user.html
{% extends "base.html" %}

{% block title %}Flasky - {{ user.username }}{% endblock %}

{% block head %}
{{ super() }}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/Jcrop.css') }}">
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/mdb.min.css') }}">
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/bootstrap-slider.min.css') }}">
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/user/profile.css') }}">
<style>
#ex1Slider .slider-selection {
    background: #BABABA;
}

}
</style>
{% endblock %}

{% block page_content %}
<div class="page-header">

    <div class="col-md-4">
        <div class="view overlay hm-black-strong">
            <img class="img img-responsive" src="{{ url_for('static', filename='img/x-23.jpg') }}" id="target">
            <div class="mask flex-center">
                <p class="white-text" >change image</p>
            </div>

            <form method="post" id="crop_form" enctype="multipart/form-data">
                <input type="hidden" name="cropx" id="cropx" value="0" />
                <input type="hidden" name="cropy" id="cropy" value="0" />
                <input type="hidden" name="cropw" id="cropw" value="0" />
                <input type="hidden" name="croph" id="croph" value="0" />
                <div id="photo-input-container">
                    <input type="file" id="user-photo" name=photo accept="image/*" style="display: none;" />
                </div>
            </form>

        </div>

        <!-- Trigger the modal with a button -->
        <button type="button" class="btn btn-info btn-lg btn-modal" data-toggle="modal" data-target="#myModal" style="display: none;">Open Modal</button>

        <!-- Modal -->
        <div id="myModal" class="modal fade" role="dialog">
            <div class="modal-dialog">

            <!-- Modal content-->

            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h3 class="modal-title">调整照片的位置和尺寸</h3>
                </div>
                <div class="modal-body">
                    <div id="image-container">
                        <img class="img" src="#" id="img-preview" alt="user-image" style="width: inherit; height: 256px;">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default submit-photo-btn" data-dismiss="modal">确定</button>
                </div>
            </div>

          </div>
        </div>
    </div>

    <div class="col-md-８">
        <div class="profile-header">
            <h1>{{ user.username }}</h1>
            {% if user.name or user.location %}
            <p>
                {% if user.name %}{{ user.name }}{% endif %}
                {% if user.location %}
                    From <a href="http://maps.baidu.com/?q={{ user.location }}">{{ user.location }}</a>
                {% endif %}
            </p>
            {% endif %}
            <p><a href="mailto:{{ user.email }}">{{ user.email }}</a></p>
            {% if user.about_me %}<p>{{ user.about_me }}</p>{% endif %}
            <p>Member since {{ moment(user.date_joined).format('L') }}. Last seen {{ moment(user.last_seen).fromNow() }}.</p>
            <p>
                {% if user == current_user %}
                <a class="btn btn-default" href="{{ url_for('.edit_profile') }}">Edit Profile</a>
                {% endif %}
            </p>
        </div>
    </div>

</div>

{% endblock %}

{% block scripts %}
{{ super() }}
<script src="/static/js/Jcrop.js"></script>
<script src="/static/js/mdb.min.js"></script>
<script src="/static/js/bootstrap-slider.min.js"></script>
<script src="/static/js/jquery.ae.image.resize.min.js"></script>
<script type="text/javascript">
    $(document).ready(function(){

        var jcrop_api;

        function initJcrop(){
            $('#img-preview').Jcrop({
                setSelect: [ 0, 0, 256, 256],
                aspectRatio: 1,
                canResize: false,
                allowSelect: false,
                onChange: setFromCoords
                }, function(){
                    jcrop_api = this;
            });
        };

        $(".white-text").click(function() {
            $("input[id='user-photo']").click();
        });

        $("input[id='user-photo']").change(function() {
            if (this.files && this.files[0]) {

                if(jcrop_api){
                    jcrop_api.destroy();
                }

                var reader = new FileReader();

                reader.readAsDataURL(this.files[0]);

                reader.onload = function (e) {
                    $('#img-preview').attr('src', e.target.result);
                    initJcrop()
                };
            };

            $(".btn-modal").click();
            $(this).val("");
        });

        function setFromCoords(obj){
            $("#cropx").val(obj.x);
            $("#cropy").val(obj.y);
            $("#cropw").val(obj.w);
            $("#croph").val(obj.h);
        };

        $('#img-preview').on('cropstart cropmove cropend', function(){
            console.log(obj.x, obj.y, obj.w, obj.h);

            // console.log(e,s,c);
            // @todo: do something useful with c
            // { x: 10, y: 10, x2: 30, y2: 30, w: 20, h: 20 }
            // c.x, c.y, c.w, c.h, ...
            // or access s.selectionApiMethod() or s.core.apiMethod() etc
            // compare event type with e.type (e.g. in if conditional, switch block)

        });

        $('.submit-photo-btn').click(function(){
            $('form#crop_form').submit();
            console.log($('form#crop_form').serialize());
        });

        $('form#crop_form').submit(function(){
            var formData = new FormData($(this)[0]);
            $.ajax({
                url: "{{ url_for('users.upload_image', username=user.username) }}",
                type: 'post',
                data: formData,
                cache: false,
                contentType: false,
                processData: false,
                success: function(data) {
                           alert("hello");
                }
            });
        });
    });


</script>
{% endblock %}

app/templates/users/user_temp.html
{% extends "base.html" %}

{% block title %}Flasky - {{ user.username }}{% endblock %}

{% block head %}
{{ super() }}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/Jcrop.css') }}">
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/mdb.min.css') }}">
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/bootstrap-slider.min.css') }}">
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/user/profile.css') }}">
<style>
#ex1Slider .slider-selection {
    background: #BABABA;
}
</style>
{% endblock %}

{% block page_content %}
<input type="file" id="user-photo" name=photo accept="image/*"/>

<img class="img" src="#" id="img-preview" alt="user-image">

{% endblock %}

{% block scripts %}
{{ super() }}
<script src="/static/js/Jcrop.js"></script>
<script src="/static/js/mdb.min.js"></script>
<script src="/static/js/bootstrap-slider.min.js"></script>
<script src="/static/js/jquery.ae.image.resize.min.js"></script>
<script type="text/javascript">
    $(document).ready(function(){

        function readURL(input) {

            if (input.files && input.files[0]) {
                var reader = new FileReader();
                console.log(input.files[0]);

                reader.readAsDataURL(input.files[0]);

                console.log(reader);

                reader.onload = function (e) {
                    $('#img-preview').attr('src', e.target.result);
                };
            }
        };

        $("input[id='user-photo']").change(function() {
            readURL(this);
            $(this).val("")
        });

    });


</script>
{% endblock %}